version: '3.8'
services:
  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 50000:5000
    volumes:
      - jenkins_home:/*
    networks:
      - jenkins_network

networks:
  jenkins_network:
volumes:
  jenkins_home:
